// src/components/PrintAreaDrawer.tsx
import L from 'leaflet'
import { useEffect, useRef } from 'react'
import { useMap, useMapEvents } from 'react-leaflet'

interface PrintAreaDrawerProps {
  isDrawing: boolean
  printBounds: L.LatLngBounds | null
  onBoundsSet: (bounds: L.LatLngBounds) => void
}

function PrintAreaDrawer({ isDrawing, printBounds, onBoundsSet }: PrintAreaDrawerProps) {
  const map = useMap()
  const drawingRef = useRef(false)
  const startLatLngRef = useRef<L.LatLng | null>(null)
  const activeRectRef = useRef<L.Rectangle | null>(null)
  const displayRectRef = useRef<L.Rectangle | null>(null)

  // Cursor style
  useEffect(() => {
    map.getContainer().style.cursor = isDrawing ? 'crosshair' : ''
  }, [isDrawing, map])

  // Clean up drawing state when draw mode is cancelled
  useEffect(() => {
    if (!isDrawing) {
      if (drawingRef.current) {
        map.dragging.enable()
        drawingRef.current = false
        startLatLngRef.current = null
      }
      if (activeRectRef.current) {
        map.removeLayer(activeRectRef.current)
        activeRectRef.current = null
      }
    }
  }, [isDrawing, map])

  // Show/update the persistent selection rectangle
  useEffect(() => {
    if (displayRectRef.current) {
      map.removeLayer(displayRectRef.current)
      displayRectRef.current = null
    }
    if (printBounds && !isDrawing) {
      displayRectRef.current = L.rectangle(printBounds, {
        color: '#3b82f6',
        weight: 2,
        fillOpacity: 0.06,
        dashArray: '6,4'
      }).addTo(map)
    }
    return () => {
      if (displayRectRef.current) {
        map.removeLayer(displayRectRef.current)
        displayRectRef.current = null
      }
    }
  }, [printBounds, isDrawing, map])

  // Global mouseup so the draw completes even if mouse leaves the map
  useEffect(() => {
    if (!isDrawing) return

    const handleMouseUp = () => {
      if (!drawingRef.current || !startLatLngRef.current) return
      map.dragging.enable()
      drawingRef.current = false
      const bounds = activeRectRef.current?.getBounds()
      startLatLngRef.current = null
      if (activeRectRef.current) {
        map.removeLayer(activeRectRef.current)
        activeRectRef.current = null
      }
      if (bounds?.isValid()) {
        const sw = bounds.getSouthWest()
        const ne = bounds.getNorthEast()
        // Reject single-point clicks (no meaningful area)
        if (Math.abs(sw.lat - ne.lat) > 0.0001 || Math.abs(sw.lng - ne.lng) > 0.0001) {
          onBoundsSet(bounds)
        }
      }
    }

    window.addEventListener('mouseup', handleMouseUp)
    return () => window.removeEventListener('mouseup', handleMouseUp)
  }, [isDrawing, map, onBoundsSet])

  useMapEvents({
    mousedown: (e) => {
      if (!isDrawing) return
      map.dragging.disable()
      drawingRef.current = true
      startLatLngRef.current = e.latlng
      if (activeRectRef.current) map.removeLayer(activeRectRef.current)
      activeRectRef.current = L.rectangle(L.latLngBounds(e.latlng, e.latlng), {
        color: '#3b82f6',
        weight: 2,
        fillOpacity: 0.12,
        dashArray: '6,4'
      }).addTo(map)
    },
    mousemove: (e) => {
      if (!drawingRef.current || !startLatLngRef.current || !activeRectRef.current) return
      activeRectRef.current.setBounds(L.latLngBounds(startLatLngRef.current, e.latlng))
    }
  })

  return null
}

export default PrintAreaDrawer

// src/components/PrintAreaDrawer.vue
<script setup lang="ts">
import L from 'leaflet'
import { onMounted, onUnmounted, watch } from 'vue'

const props = defineProps<{
  map: L.Map
  isDrawing: boolean
  printBounds: L.LatLngBounds | null
}>()

const emit = defineEmits<{ 'bounds-set': [bounds: L.LatLngBounds] }>()

let drawingActive = false
let startLatLng: L.LatLng | null = null
let activeRect: L.Rectangle | null = null
let displayRect: L.Rectangle | null = null

watch(
  () => props.isDrawing,
  (drawing) => {
    props.map.getContainer().style.cursor = drawing ? 'crosshair' : ''
    if (!drawing) {
      if (drawingActive) {
        props.map.dragging.enable()
        drawingActive = false
        startLatLng = null
      }
      if (activeRect) {
        props.map.removeLayer(activeRect)
        activeRect = null
      }
    }
  }
)

watch(
  () => [props.printBounds, props.isDrawing] as const,
  ([bounds, drawing]) => {
    if (displayRect) {
      props.map.removeLayer(displayRect)
      displayRect = null
    }
    if (bounds && !drawing) {
      displayRect = L.rectangle(bounds, {
        color: '#3b82f6',
        weight: 2,
        fillOpacity: 0.06,
        dashArray: '6,4'
      }).addTo(props.map)
    }
  }
)

function handleMouseDown(e: L.LeafletMouseEvent) {
  if (!props.isDrawing) return
  props.map.dragging.disable()
  drawingActive = true
  startLatLng = e.latlng
  if (activeRect) props.map.removeLayer(activeRect)
  activeRect = L.rectangle(L.latLngBounds(e.latlng, e.latlng), {
    color: '#3b82f6',
    weight: 2,
    fillOpacity: 0.12,
    dashArray: '6,4'
  }).addTo(props.map)
}

function handleMouseMove(e: L.LeafletMouseEvent) {
  if (!drawingActive || !startLatLng || !activeRect) return
  activeRect.setBounds(L.latLngBounds(startLatLng, e.latlng))
}

function handleMouseUp() {
  if (!drawingActive || !startLatLng) return
  props.map.dragging.enable()
  drawingActive = false
  const bounds = activeRect?.getBounds()
  startLatLng = null
  if (activeRect) {
    props.map.removeLayer(activeRect)
    activeRect = null
  }
  if (bounds?.isValid()) {
    const sw = bounds.getSouthWest()
    const ne = bounds.getNorthEast()
    if (Math.abs(sw.lat - ne.lat) > 0.0001 || Math.abs(sw.lng - ne.lng) > 0.0001) {
      emit('bounds-set', bounds)
    }
  }
}

onMounted(() => {
  props.map.on('mousedown', handleMouseDown as L.LeafletEventHandlerFn)
  props.map.on('mousemove', handleMouseMove as L.LeafletEventHandlerFn)
  window.addEventListener('mouseup', handleMouseUp)
})

onUnmounted(() => {
  props.map.off('mousedown', handleMouseDown as L.LeafletEventHandlerFn)
  props.map.off('mousemove', handleMouseMove as L.LeafletEventHandlerFn)
  window.removeEventListener('mouseup', handleMouseUp)
  if (displayRect) props.map.removeLayer(displayRect)
  if (activeRect) props.map.removeLayer(activeRect)
})
</script>

<template></template>
