// src/components/TileLayerSelector.tsx
import { TileLayer } from 'react-leaflet'

import { MAP_STYLE_CONFIGS, MapStyle } from '../types'

interface TileLayerSelectorProps {
  style: MapStyle
}

function TileLayerSelector({ style }: TileLayerSelectorProps) {
  const config = MAP_STYLE_CONFIGS[style]
  return (
    <TileLayer
      key={style}
      url={config.url}
      attribution={config.attribution}
      {...(config.subdomains ? { subdomains: config.subdomains } : {})}
    />
  )
}

export default TileLayerSelector

// src/components/TileLayerSelector.vue
<script setup lang="ts">
import { LTileLayer } from '@vue-leaflet/vue-leaflet'
import { computed } from 'vue'

import { MAP_STYLE_CONFIGS, MapStyle } from '../types'

const props = defineProps<{ style: MapStyle }>()
const config = computed(() => MAP_STYLE_CONFIGS[props.style])
</script>

<template>
  <LTileLayer
    :key="style"
    :url="config.url"
    :attribution="config.attribution"
    :subdomains="config.subdomains ?? ''"
  />
</template>
